# Generated by Django 3.1.3 on 2020-11-12 10:47

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FilmWork",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                (
                    "creation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="дата выпуска"
                    ),
                ),
                (
                    "certificate",
                    models.TextField(
                        blank=True, null=True, verbose_name="возрастной ценз"
                    ),
                ),
                (
                    "file_path",
                    models.TextField(blank=True, null=True, verbose_name="файл"),
                ),
                (
                    "rating",
                    models.FloatField(blank=True, null=True, verbose_name="рейтинг"),
                ),
                (
                    "type",
                    models.TextField(
                        blank=True,
                        choices=[("movie", "фильм"), ("tv_series", "сериал")],
                        null=True,
                        verbose_name="тип",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кинокартина",
                "verbose_name_plural": "Кинокартина",
                "db_table": "film_work",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField(max_length=255, verbose_name="название")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="описание"),
                ),
            ],
            options={
                "verbose_name": "Жанр",
                "verbose_name_plural": "Жанры",
                "db_table": "genres",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(db_index=True, max_length=255, verbose_name="имя"),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Участник кинокартины",
                "verbose_name_plural": "Участники кинокартины",
                "db_table": "persons",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="FilmWorksPersons",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.TextField(
                        choices=[
                            ("director", "режиссер"),
                            ("actor", "актер"),
                            ("writer", "сценарист"),
                        ]
                    ),
                ),
                (
                    "film_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="film_works.filmwork",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="film_works.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кинокартины и участники",
                "verbose_name_plural": "Кинокартины и участники",
                "db_table": "film_works_persons",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="FilmWorksGenres",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "film_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="film_works.filmwork",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="film_works.genre",
                    ),
                ),
            ],
            options={"db_table": "film_works_genres", "ordering": ("id",)},
        ),
        migrations.AddField(
            model_name="filmwork",
            name="genres",
            field=models.ManyToManyField(
                through="film_works.FilmWorksGenres", to="film_works.Genre"
            ),
        ),
        migrations.AddField(
            model_name="filmwork",
            name="persons",
            field=models.ManyToManyField(
                through="film_works.FilmWorksPersons", to="film_works.Person"
            ),
        ),
        migrations.AddConstraint(
            model_name="filmworkspersons",
            constraint=models.UniqueConstraint(
                fields=("film_work", "person", "role"),
                name="unique_film_work_person_role",
            ),
        ),
        migrations.AddConstraint(
            model_name="filmworksgenres",
            constraint=models.UniqueConstraint(
                fields=("film_work", "genre"), name="unique_film_work_genre"
            ),
        ),
    ]
